# Generated by Django 2.2.7 on 2019-11-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(max_length=50)),
                ('Y', models.CharField(max_length=50)),
                ('unique_squirrel_id', models.CharField(max_length=100)),
                ('Hectare', models.CharField(max_length=10)),
                ('Shift', models.CharField(max_length=10)),
                ('Date', models.IntegerField()),
                ('Age', models.CharField(max_length=50)),
                ('Primary_Fur_Color', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=100)),
                ('Specific_Location', models.CharField(max_length=100)),
                ('Running', models.BooleanField(default=False)),
                ('Chasing', models.BooleanField(default=False)),
                ('Climbing', models.BooleanField(default=False)),
                ('Eating', models.BooleanField(default=False)),
                ('Foraging', models.BooleanField(default=False)),
                ('Other_Activities', models.CharField(max_length=100)),
                ('Kuks', models.BooleanField(default=False)),
                ('Quaas', models.BooleanField(default=False)),
                ('Moans', models.BooleanField(default=False)),
                ('Tail_Flags', models.BooleanField(default=False)),
                ('Tail_Twitches', models.BooleanField(default=False)),
                ('Approaches', models.BooleanField(default=False)),
                ('Indifferent', models.BooleanField(default=False)),
                ('Runs_From', models.BooleanField(default=False)),
            ],
        ),
    ]
