# Generated by Django 2.2.7 on 2019-12-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='unique_squirrel_id',
            new_name='Unique_Squirrel_ID',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='Hectare',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Approaches',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Chasing',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Climbing',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Eating',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Foraging',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Indifferent',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Kuks',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Moans',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Primary_Fur_Color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Quaas',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Running',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Runs_From',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Tail_Flags',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Tail_Twitches',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='X',
            field=models.DecimalField(decimal_places=25, max_digits=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Y',
            field=models.DecimalField(decimal_places=25, max_digits=50),
        ),
    ]
