# Generated by Django 2.2.7 on 2019-12-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191203_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Date',
            field=models.DateField(),
        ),
    ]
