# Generated by Django 2.2.7 on 2019-12-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20191203_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='Unique_Squirrel_ID',
            new_name='unique_squirrel_id',
        ),
    ]
