# Generated by Django 2.2.7 on 2019-12-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_auto_20191207_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', ''), ('Unknown', '?')], help_text='Age', max_length=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Approaches',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Approaches', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Chasing',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Chasing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Climbing',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Climbing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Date',
            field=models.DateField(help_text='Date'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Eating',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Eating', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Foraging',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Foraging', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Indifferent',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Indifferent', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Kuks',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Kuks', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('', '')], help_text='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Moans',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Moans', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('', '')], help_text='Primary Fur Color', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Quaas',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Quaas', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Running',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Running', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Runs_From',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Runs From', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Tail_Flags',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Tail Flags', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Tail_Twitches',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Tail Twitches', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='X',
            field=models.DecimalField(decimal_places=20, help_text='X', max_digits=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Y',
            field=models.DecimalField(decimal_places=20, help_text='Y', max_digits=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.CharField(help_text='unique squirrel id', max_length=100),
        ),
    ]
