# Generated by Django 2.2.7 on 2019-12-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_auto_20191208_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='X',
            field=models.DecimalField(decimal_places=20, help_text='Longitude', max_digits=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Y',
            field=models.DecimalField(decimal_places=20, help_text='Latitude', max_digits=50),
        ),
    ]
